server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: zxc
          uri: lb://BOOK-SERVICE
          predicates:
            - Method=GET
            - Path=/ping
          filters:
            - RoleAuth=USER


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
