server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: zxc
          uri: lb://BOOK-SERVICE
          predicates:
            - Method=POST
            - Path=/order
          filters:
            - name: RoleAuth
              args:
                roles:
                  - USER
                  - ADMIN

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
